### ISSUE TITLE
'continue' does not work in for loops

### ISSUE THREAD

**Issue by alexanderuv** [NSHipster/swift-gyb#1]
Kudos on this tool! I am trying to use it to generate some bindings based on XML and I ran into this issue. Here's a sample code:

```swift
public class Demo {
% for item in 'name', 'lastName', 'id':
%   if item == 'id':
%       continue
%   end
    var ${item}: String
% end
}
```

The output I get is:
```
  File "/Users/alexander/dev/apple/swift-project/vulkanSwift/Sources/SwiftVulkan/Demo.swift.gyb", line 4
    % for item in 'name', 'lastName', 'id':
SyntaxError: 'continue' not properly in loop
```

**Comment by alexanderuv** [comment]
For now, I will just invert the `if` condition 🙂

**Comment by mattt** [comment]
Unfortunately, GYB isn't particularly helpful when it comes to determining why something doesn't work. I don't believe the issue you're encountering is specific to `swift-gyb` rather than GYB itself, so there's nothing to be done from this end. If this is still a problem, you could try asking the Swift / GYB maintainers about this issue (though I don't think they're actively developing or supporting it beyond their own usage).
